---
- name: Verificar contenido del certificado en EE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Mostrar contenido del certificado
      command: cat /etc/conjur/conjur.crt
      register: cert_output
      ignore_errors: true

    - name: Mostrar resultado del cat
      debug:
        var: cert_output
