---
- name: Obtener secreto desde Conjur
  hosts: localhost
  gather_facts: false

  vars:
    my_password: "{{ lookup('conjur', 'secrets/awx-cka04/api-key') }}"

  tasks:
    - name: Mostrar secreto
      debug:
        msg: "La contraseña es {{ my_password }}"
