---
- name: Test lookup from Conjur
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Mostrar secreto desde Conjur
      debug:
        msg: "{{ lookup('cyberark.conjur', 'secrets/awx-cka04/api-key') }}"
