- name: Prueba de recuperación de secreto desde Conjur
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Obtener secreto desde Conjur
      debug:
        msg: >-
          {{ lookup('community.general.conjur', 'secrets/awx-cka04/api-key') }}
