---
- name: Verificar API Key en entorno de ejecución
  hosts: localhost
  gather_facts: false

  vars:
    conjur_api_key: "{{ lookup('env', 'CONJUR_AUTHN_API_KEY') }}"

  tasks:
    - name: Mostrar API Key inyectada
      debug:
        msg: "API Key es: {{ conjur_api_key | default('NO DEFINIDA') }}"
