- name: Prueba Conjur desde colección oficial
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar secreto desde Conjur
      debug:
        msg: >-
          {{ lookup('cyberark.conjur.conjur_variable', 'secrets/awx-cka04/api-key') }}
