- name: Mostrar secreto desde Conjur
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Mostrar secreto desde Conjur
      debug:
        msg: "{{ lookup('cyberark.conjur.conjur_variable', 'secrets/awx-cka04/api-key') }}"
